parameters:
  tax_handler.class: Heystack\Tax\TaxHandler
  tax_handler_subscriber.class: Heystack\Tax\Subscriber
  
services:
  tax_handler:
    class: %tax_handler.class%
    arguments: [ @state, @event_dispatcher, @locale_service, @purchasableholder, @currency_service ]
    tags:
      - { name: ss_orm_backend.reference_data_provider }
      - { name: transaction.modifier }
      - { name: state.restore }
      
  tax_handler_subscriber:
    class: %tax_handler_subscriber.class%
    arguments: [ @event_dispatcher, @tax_handler, @state ]
    tags:
      - { name: event_dispatcher.subscriber }
      
  tax_transaction_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-tax/config/storage/tax_transaction.yml ]
    tags:
      - { name: schema }
      - { name: autoinject, arguments: true }
      
  tax_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-tax/config/storage/tax.yml ]
    tags:
      - { name: schema, reference: true }
      - { name: autoinject, arguments: true }
      